# Description et Prétraitement des Données

Ce notebook contient la description et le prétraitement du dataset marocain fourni. Nous utiliserons les bibliothèques Pandas et NumPy pour explorer et préparer les données.

## Description des données

Imorter les bibliothèques nécessaires

In [4]:
import pandas as pd
import numpy as np

Lire le fichier

In [5]:
df = pd.read_parquet('Date_final_dataset_balanced_float32.parquet')

Afficher les informations du dataset

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 934586 entries, 0 to 934585
Columns: 278 entries, acq_date to is_fire
dtypes: datetime64[ns](1), float32(277)
memory usage: 994.7 MB

Afficher un aperçu du dataset

In [7]:
df.head()

,acq_date,latitude,longitude,is_holiday,day_of_week,day_of_year,is_weekend,NDVI,SoilMoisture,sea_distance,...,wind_gust_quarterly_mean,dew_point_quarterly_mean,average_temperature_yearly_mean,maximum_temperature_yearly_mean,minimum_temperature_yearly_mean,precipitation_yearly_mean,snow_depth_yearly_mean,wind_gust_yearly_mean,dew_point_yearly_mean,is_fire
0,2015-05-28,31.390602,-4.254445,0.0,3.0,148.0,0.0,1139.0,7.0,464731.937500,...,882.085571,27.641111,71.703011,82.031784,58.668766,2.213260,999.900024,857.071777,32.760273,1.0
1,2017-12-05,33.832943,-5.188356,0.0,1.0,339.0,0.0,3223.0,31.0,186799.984375,...,936.817383,52.452175,65.621719,80.128555,53.295628,2.256421,999.900024,864.048340,47.819126,1.0
2,2021-11-19,35.385689,-5.684218,0.0,4.0,323.0,0.0,4987.0,30.0,44937.300781,...,884.289124,65.556519,66.108742,74.353828,58.815575,0.050738,999.900024,806.456848,56.298634,1.0
3,2014-04-19,30.122351,-7.498038,0.0,5.0,109.0,1.0,991.0,12.5,231336.125000,...,839.094421,21.176111,69.008766,82.659180,54.666027,0.005205,999.900024,771.132629,26.421097,0.0
4,2014-04-11,30.221554,-9.154314,0.0,4.0,101.0,0.0,2171.0,18.0,51333.945312,...,945.704468,46.408890,66.195618,79.167122,54.768494,0.032082,999.900024,951.709595,52.842464,1.0

Afficher les statistiques descriptives du dataset

In [8]:
df.describe()

,acq_date,latitude,longitude,is_holiday,day_of_week,day_of_year,is_weekend,NDVI,SoilMoisture,sea_distance,...,wind_gust_quarterly_mean,dew_point_quarterly_mean,average_temperature_yearly_mean,maximum_temperature_yearly_mean,minimum_temperature_yearly_mean,precipitation_yearly_mean,snow_depth_yearly_mean,wind_gust_yearly_mean,dew_point_yearly_mean,is_fire
count,934586,934586.000000,934586.000000,934586.000000,934586.000000,934586.000000,934586.000000,934586.000000,934586.000000,934586.000000,...,934586.000000,934586.000000,934586.000000,934586.000000,934586.000000,934586.000000,934586.000000,934586.000000,934586.000000,934586.0
mean,2018-02-11 14:49:51.211081472,32.793350,-6.055579,0.062526,2.976634,194.607834,0.282150,2639.589844,20.082907,140767.546875,...,872.539551,67.082825,66.840477,77.929955,59.793640,1.218641,999.864441,879.436035,85.134514,0.5
min,2013-01-31 00:00:00,27.074949,-12.044235,0.000000,0.000000,1.000000,0.000000,-765.000000,0.000000,0.000000,...,13.169967,17.941111,51.708469,63.495628,41.978142,0.000000,997.162720,55.930412,26.421097,0.0
25%,2015-09-16 00:00:00,31.421812,-7.749783,0.000000,1.000000,121.000000,0.000000,1308.000000,11.000000,49483.511719,...,827.229980,42.710869,64.644806,74.977325,52.585480,0.052090,999.900024,848.476135,47.557259,0.0
50%,2018-03-10 00:00:00,33.368835,-5.626343,0.000000,3.000000,206.000000,0.000000,2240.000000,17.500000,79821.320312,...,924.950562,50.806595,66.522057,77.053696,55.054520,0.554986,999.900024,903.814453,50.807671,0.5
75%,2020-08-18 00:00:00,34.670555,-4.479708,0.000000,5.000000,268.000000,1.000000,3625.000000,27.000000,210482.031250,...,999.900024,55.703297,69.074860,80.613937,58.807652,1.667041,999.900024,989.327332,54.635067,1.0
max,2022-12-23 00:00:00,35.915291,-1.656559,1.000000,6.000000,366.000000,1.000000,8432.000000,99.000000,553629.937500,...,999.900024,9890.538086,78.635201,133.978638,213.562561,20.853014,999.900024,999.900024,9536.286133,1.0
std,NaN,2.302324,2.398227,0.242109,2.011039,94.253609,0.449208,1554.052734,12.918498,124798.367188,...,169.851944,277.602966,2.979686,4.958928,15.354151,1.811131,6.784895,153.505630,277.867645,0.5

Le dataset contient les colonnes suivantes :
- Marqueurs temporels : acq_date, day_of_week, day_of_year et les indicateurs liés aux jours fériés (is_holiday, is_weekend).
- Caractéristiques spatiales : latitude, longitude et sea_distance.
- Conditions environnementales : NDVI pour la santé de la végétation et SoilMoisture.
- Données météorologiques : average_temperature, maximum_temperature, minimum_temperature, precipitation, snow_depth, wind_speed et plus encore.
- Statistiques météorologiques agrégées : périodes hebdomadaires, mensuelles, trimestrielles et annuelles.
- Variable de résultat : is_fire indique la présence (1) ou l'absence (0) d'un incendie de forêt.

Ce dataset a été choisi en raison de sa nature complète, intégrant des données météorologiques, environnementales et spatiales pour faciliter la prédiction précise des incendies de forêt.

## Prétraitement des Données

Gestion des valeurs manquantes

In [9]:
missing_values = df.isnull().sum()
missing_values = missing_values[missing_values > 0]
missing_values.sort_values(ascending=False, inplace=True)
missing_values

Series([], dtype: int64)

Remplir les valeurs manquantes avec la moyenne de chaque colonne

In [10]:
df.fillna(df.mean(), inplace=True)

Vérifier à nouveau les valeurs manquantes

In [11]:
df.isnull().sum().sum()

0

## Normalisation des Données

Nous allons normaliser certaines colonnes pour faciliter l'analyse.

Normaliser les colonnes sélectionnées

In [12]:
columns_to_normalize = ['NDVI', 'SoilMoisture', 'average_temperature_yearly_mean', 'maximum_temperature_yearly_mean', 'minimum_temperature_yearly_mean', 'precipitation_yearly_mean']
df[columns_to_normalize] = (df[columns_to_normalize] - df[columns_to_normalize].min()) / (df[columns_to_normalize].max() - df[columns_to_normalize].min())

Afficher un aperçu des données normalisées

In [13]:
df.head()

,acq_date,latitude,longitude,is_holiday,day_of_week,day_of_year,is_weekend,NDVI,SoilMoisture,sea_distance,...,wind_gust_quarterly_mean,dew_point_quarterly_mean,average_temperature_yearly_mean,maximum_temperature_yearly_mean,minimum_temperature_yearly_mean,precipitation_yearly_mean,snow_depth_yearly_mean,wind_gust_yearly_mean,dew_point_yearly_mean,is_fire
0,2015-05-28,31.390602,-4.254445,0.0,3.0,148.0,0.0,0.207024,0.070707,464731.937500,...,882.085571,27.641111,0.742554,0.262988,0.097274,0.106136,999.900024,857.071777,32.760273,1.0
1,2017-12-05,33.832943,-5.188356,0.0,1.0,339.0,0.0,0.433620,0.313131,186799.984375,...,936.817383,52.452175,0.516708,0.235985,0.065959,0.108206,999.900024,864.048340,47.819126,1.0
2,2021-11-19,35.385689,-5.684218,0.0,4.0,323.0,0.0,0.625421,0.303030,44937.300781,...,884.289124,65.556519,0.534795,0.154054,0.098129,0.002433,999.900024,806.456848,56.298634,1.0
3,2014-04-19,30.122351,-7.498038,0.0,5.0,109.0,1.0,0.190932,0.126263,231336.125000,...,839.094421,21.176111,0.642495,0.271889,0.073945,0.000250,999.900024,771.132629,26.421097,0.0
4,2014-04-11,30.221554,-9.154314,0.0,4.0,101.0,0.0,0.319235,0.181818,51333.945312,...,945.704468,46.408890,0.538021,0.222344,0.074543,0.001538,999.900024,951.709595,52.842464,1.0